# Generated by Django 5.1.6 on 2025-03-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrer', '0002_employerprofile_jobseekerprofile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
